  <tr>
        <td width="15%">
        </td>
        <td>
            <div align="Middle">
                <font size=25px>
                    <b>  Banknote Authentication dataset Classifier using ANN with one hidden layer
                    </b>
                </font>
            </div>
        </td>
    </tr>

## Dataset
Downloaded directly from the curated repository 

## Data Definition:
 5 columns and 1372 records 

# Content

**[1. Import Python modules](#1)**<br>
**[2. DEF functions - Activation functions, Neuron Layer, Weigths and bias](#2)**<br>
**[3. Model training](#3)**<br>
**[4. Epoch def function](#4)**<br>
**[5. Model summary](#5)**<br>
**[6. Print initial and final weights](#6)**<br>


<a id='1'></a>
## Importing Libraries and Data set

In [12]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import OneHotEncoder
import pandas as pd


# Load the Banknote Authentication dataset
data = pd.read_csv(r"E:\DS workspace\ML DL Python\Happymonk\MLP model from github\Bank note\BankNote_Authentication.csv")
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values


# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# One-hot encode the target labels
encoder = OneHotEncoder(sparse=False)
y_train_encoded = encoder.fit_transform(y_train.reshape(-1, 1))
y_test_encoded = encoder.transform(y_test.reshape(-1, 1))


c:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


<a id='2'></a>
## DEF functions - Activation functions, Neuron Layer, Weigths and bias

In [13]:
# Set the initial parameters
np.random.seed(42)
m = X_train.shape[1]
n = 8
p = 4
k = len(np.unique(y_train))
epochs = 1000
learning_rate = 0.01

# Initialize the weights and biases
W1 = np.random.randn(m, n)
b1 = np.zeros((1, n))
W2 = np.random.randn(n, p)
b2 = np.zeros((1, p))
W3 = np.random.randn(p, k)
b3 = np.zeros((1, k))
K = np.random.randn(3)

# Define the activation function
def activation_function(x, k0, k1):
    return k0 + k1 * x

# Forward propagation
def forward_propagation(X, W1, b1, W2, b2, K):
    z1 = np.dot(X, W1) + b1
    a1 = activation_function(z1, K[0], K[1])
    z2 = np.dot(a1, W2) + b2
    a2 = activation_function(z2, K[0], K[1])
    z3 = np.dot(a2, W3) + b3
    a3 = softmax(z3)
    return z1, a1, z2, a2, z3, a3

# Softmax activation function
def softmax(x):
    exps = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exps / np.sum(exps, axis=1, keepdims=True)

# Backward propagation
def backward_propagation(X, y, z1, a1, z2, a2, z3, a3, W2, K):
    m = X.shape[0]
    dz3 = a3 - y
    dw3 = (1 / m) * np.dot(a2.T, dz3)
    db3 = (1 / m) * np.sum(dz3, axis=0)
    da2 = np.dot(dz3, W3.T)
    dz2 = activation_derivative(a2, K[1]) * da2
    dw2 = (1 / m) * np.dot(a1.T, dz2)
    db2 = (1 / m) * np.sum(dz2, axis=0)
    da1 = np.dot(dz2, W2.T)
    dz1 = activation_derivative(a1, K[1]) * da1
    dw1 = (1 / m) * np.dot(X.T, dz1)
    db1 = (1 / m) * np.sum(dz1, axis=0)
    dK2 = np.array([np.mean(da2), np.mean(da2 * z2), np.mean(da2 * z2**2)])
    dK1 = np.array([np.mean(da1), np.mean(da1 * z1), np.mean(da1 * z1**2)])
    dK = dK2 + dK1
    return dw1, db1, dw2, db2, dw3, db3, dK

<a id='3'></a>
## Model training

In [14]:

# Activation derivative
def activation_derivative(x, k1):
    return k1

# Training loop
train_losses = []
test_losses = []
train_accuracies = []
test_accuracies = []
f1_scores = []

for epoch in range(epochs):
    # Forward propagation
    z1, a1, z2, a2, z3, a3 = forward_propagation(X_train, W1, b1, W2, b2, K)

    # Backward propagation
    dw1, db1, dw2, db2, dw3, db3, dK = backward_propagation(X_train, y_train_encoded, z1, a1, z2, a2, z3, a3, W2, K)

    # Update parameters
    W1 -= learning_rate * dw1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dw2
    b2 -= learning_rate * db2
    W3 -= learning_rate * dw3
    b3 -= learning_rate * db3
    K -= learning_rate * dK

    # Calculate train and test loss
    _, _, _, _, _, train_predictions = forward_propagation(X_train, W1, b1, W2, b2, K)
    _, _, _, _, _, test_predictions = forward_propagation(X_test, W1, b1, W2, b2, K)
    train_loss = -np.mean(np.sum(y_train_encoded * np.log(train_predictions), axis=1))
    test_loss = -np.mean(np.sum(y_test_encoded * np.log(test_predictions), axis=1))
    train_losses.append(train_loss)
    test_losses.append(test_loss)

    # Calculate train and test accuracy
    train_accuracy = accuracy_score(y_train, np.argmax(train_predictions, axis=1))
    test_accuracy = accuracy_score(y_test, np.argmax(test_predictions, axis=1))
    train_accuracies.append(train_accuracy)
    test_accuracies.append(test_accuracy)

    # Calculate F1-Score
    f1 = f1_score(y_test, np.argmax(test_predictions, axis=1), average='weighted')
    f1_scores.append(f1)

<a id='4'></a>
## Epoch def function

In [15]:

for epoch in range(epochs):
    # Forward propagation
    z1, a1, z2, a2, z3, a3 = forward_propagation(X_train, W1, b1, W2, b2, K)

    # Backward propagation
    dw1, db1, dw2, db2, dw3, db3, dK = backward_propagation(X_train, y_train_encoded, z1, a1, z2, a2, z3, a3, W2, K)

    # Update parameters
    W1 -= learning_rate * dw1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dw2
    b2 -= learning_rate * db2
    W3 -= learning_rate * dw3
    b3 -= learning_rate * db3
    K -= learning_rate * dK

    # Calculate train and test loss
    _, _, _, _, _, train_predictions = forward_propagation(X_train, W1, b1, W2, b2, K)
    _, _, _, _, _, test_predictions = forward_propagation(X_test, W1, b1, W2, b2, K)
    train_loss = -np.mean(np.sum(y_train_encoded * np.log(train_predictions), axis=1))
    test_loss = -np.mean(np.sum(y_test_encoded * np.log(test_predictions), axis=1))
    train_losses.append(train_loss)
    test_losses.append(test_loss)

    # Calculate train and test accuracy
    train_accuracy = accuracy_score(y_train, np.argmax(train_predictions, axis=1))
    test_accuracy = accuracy_score(y_test, np.argmax(test_predictions, axis=1))
    train_accuracies.append(train_accuracy)
    test_accuracies.append(test_accuracy)

    # Calculate F1-Score
    f1 = f1_score(y_test, np.argmax(test_predictions, axis=1), average='weighted')
    f1_scores.append(f1)

<a id='5'></a>
## Model summary

In [16]:
# Model summary
print("\nModel Summary:")
print("Number of features:", m)
print("Number of hidden nodes:", n)
print("Number of output nodes:", k)
print("Number of training examples:", X_train.shape[0])
print("Number of test examples:", X_test.shape[0])
print("Number of epochs:", epochs)


Model Summary:
Number of features: 4
Number of hidden nodes: 8
Number of output nodes: 2
Number of training examples: 1096
Number of test examples: 275
Number of epochs: 1000


<a id='7'></a>
## Print initial and final weights

In [18]:
# Print initial and final weights
print("Initial Weights:")
print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)
print("W3:\n", W3)
print("b3:\n", b3)
print("K:\n", K)
print("\nFinal Weights:")
print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)
print("W3:\n", W3)
print("b3:\n", b3)
print("K:\n", K)

Initial Weights:
W1:
 [[ 0.63540203 -0.09535129  0.63272378  1.51729196 -0.12047677 -0.27462461
   1.56774133  0.81283306]
 [-0.42394748  0.51913835 -0.48490168 -0.45185685  0.2746626  -1.86511179
  -1.68715956 -0.57459632]
 [-0.84516675  0.38189643 -0.92112156 -1.41932565  1.60345755 -0.29908145
   0.04022099 -1.35529317]
 [-0.44129968  0.14218005 -1.15952348  0.36902457 -0.5185287  -0.32538224
  -0.61433177  1.88676441]]
b1:
 [[-0.29687453 -0.10538176  0.05024016 -0.0035781  -0.2640211   0.07953984
   0.0029589  -0.09849247]]
W2:
 [[ 0.00706252 -1.01017751  0.79005364 -1.16758938]
 [ 0.18902981 -1.9930427  -1.29822106  0.16634437]
 [ 0.7673436   0.23995278 -0.16145651 -0.22862191]
 [-1.47568588 -0.71839065 -0.45812821  1.05867647]
 [ 0.31534461 -1.83824956  0.36334103 -0.4611502 ]
 [-0.62593277  0.67487781  0.95065728  0.98416051]
 [-0.82954275 -0.34907267  0.31914979  0.92312594]
 [-0.4816247  -0.20411319 -1.0939446  -1.21788733]]
b2:
 [[ 0.03132435  0.07535514 -0.0473796   0.070511